//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessosPortaria
    {
        public int idAcesso { get; set; }
        public string PlacaAcesso { get; set; }
        public string Placa2Acesso { get; set; }
        public string NomeMotoristaAcesso { get; set; }
        public System.DateTime EntradaAcesso { get; set; }
        public Nullable<System.DateTime> SaidaAcesso { get; set; }
        public string ObservacaoAcesso { get; set; }
        public string LacreAcesso { get; set; }
        public int KmAcesso { get; set; }
        public string EstadoGeral { get; set; }
        public Nullable<int> DocaAcesso { get; set; }
        public Nullable<int> PorteiroEntrada { get; set; }
        public Nullable<int> PorteiroSaida { get; set; }
    
        public virtual Veiculos Veiculos { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Funcionarios Funcionarios1 { get; set; }
    }
}
