//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessosPortaria
    {
        public string idAcesso { get; set; }
        public string MotoristaAcesso { get; set; }
        public System.DateTime EntradaAcesso { get; set; }
        public System.DateTime SaidaAcesso { get; set; }
        public string ObservacaoAcesso { get; set; }
        public string LacreAcesso { get; set; }
        public int KmAcesso { get; set; }
        public string EstadoGeral { get; set; }
        public int DocaAcesso { get; set; }
    
        public virtual Veiculos Veiculos { get; set; }
    }
}
