//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divergencias
    {
        public int idDivergencia { get; set; }
        public int TarefaDivergencia { get; set; }
        public string TipoDivergencia { get; set; }
        public string QtdeDivergencia { get; set; }
        public string TextoDivergencia { get; set; }
    
        public virtual Tarefas Tarefas { get; set; }
    }
}
