//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manifestos()
        {
            this.Cte_Manifesto = new HashSet<Cte_Manifesto>();
            this.Tarefas = new HashSet<Tarefas>();
        }
    
        public int numeroManifesto { get; set; }
        public int quantCtesManifesto { get; set; }
        public double pesoManifesto { get; set; }
        public int VolumesManifesto { get; set; }
        public Nullable<int> skusManifesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cte_Manifesto> Cte_Manifesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefas> Tarefas { get; set; }
    }
}
