//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscais
    {
        public int idNF { get; set; }
        public string numeroNF { get; set; }
        public string fonecedorNF { get; set; }
        public int volumesNF { get; set; }
        public int skuNF { get; set; }
        public Nullable<int> CteNF { get; set; }
        public string clienteNF { get; set; }
    
        public virtual Ctes Ctes { get; set; }
    }
}
