//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasManifestos
    {
        public int Manifesto { get; set; }
        public string numeroNF { get; set; }
        public string fonecedorNF { get; set; }
        public int volumesNF { get; set; }
        public Nullable<int> CteNF { get; set; }
        public int quantCtesManifesto { get; set; }
        public int VolumesManifesto { get; set; }
        public Nullable<int> skusManifesto { get; set; }
    }
}
