//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int idTarefa { get; set; }
        public System.DateTime inicioTarefa { get; set; }
        public Nullable<float> Pontuacao { get; set; }
        public string nomeFunc { get; set; }
        public string tipoTarefa { get; set; }
    }
}
