//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioConferencias
    {
        public int idTarefa { get; set; }
        public int documentoTarefa { get; set; }
        public string tipoTarefa { get; set; }
        public System.DateTime inicioTarefa { get; set; }
        public Nullable<System.DateTime> fimTarefa { get; set; }
        public string divergenciaTarefa { get; set; }
        public string nomeFunc { get; set; }
        public int volumesNF { get; set; }
        public int skuNF { get; set; }
        public string fonecedorNF { get; set; }
        public int numeroCte { get; set; }
    }
}
