//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioNaoConferencia
    {
        public int idTarefa { get; set; }
        public int documentoTarefa { get; set; }
        public System.DateTime inicioTarefa { get; set; }
        public Nullable<System.DateTime> fimTarefa { get; set; }
        public string tipoTarefa { get; set; }
        public string nomeFunc { get; set; }
        public int VolumesManifesto { get; set; }
        public int skusManifesto { get; set; }
        public int quantCtesManifesto { get; set; }
        public string divergenciaTarefa { get; set; }
        public int numeroManifesto { get; set; }
        public Nullable<int> quantPaletizado { get; set; }
        public Nullable<int> totalPaletes { get; set; }
    }
}
