//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdusisBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veiculos()
        {
            this.AcessosPortaria = new HashSet<AcessosPortaria>();
        }
    
        public string PlacaVeiculo { get; set; }
        public string MotoristaVeiculo { get; set; }
        public string Placa2Veiculo { get; set; }
        public string TipoVeiculo { get; set; }
        public int CapacidadePaletes { get; set; }
        public bool AtivoVeiculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcessosPortaria> AcessosPortaria { get; set; }
    }
}
