//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class PastasXml : global::System.Configuration.ApplicationSettingsBase {
        
        private static PastasXml defaultInstance = ((PastasXml)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PastasXml())));
        
        public static PastasXml Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\thais.maria\\Documents\\xml produsis\\NF")]
        public string PastaNFs {
            get {
                return ((string)(this["PastaNFs"]));
            }
            set {
                this["PastaNFs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\thais.maria\\Documents\\xml produsis\\Manifesto")]
        public string PastaManifestos {
            get {
                return ((string)(this["PastaManifestos"]));
            }
            set {
                this["PastaManifestos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\thais.maria\\Documents\\xml produsis\\Pre Manifesto")]
        public string PastaPreManifestos {
            get {
                return ((string)(this["PastaPreManifestos"]));
            }
            set {
                this["PastaPreManifestos"] = value;
            }
        }
    }
}
